spring.application.name=${APP_NAME}
app.env=${APP_ENV}

#DATASOURCE
spring.datasource.url=${DATA_SOURCE_URL}
spring.datasource.username=${DATA_SOURCE_USERNAME}
spring.datasource.password=${DATA_SOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA CONFIG
spring.jpa.hibernate.ddl-auto=validate
#TODO desactivar en prod
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect

#LOGINLEVEL
logging.level.org.springframework.security=${LOG_LEVEL}
logging.level.root=info
logging.pattern.console=%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} level=%-5level app=${spring.application.name} env=${APP_ENV} pid=%property{PID} thread=%thread msg=%replace(%msg){'\\n','\\\\n'}%n

#configuraciones de netty
reactor.netty.http.server.access-log-enabled=true

#security.jwt.key.private=N2U1MDRiNDc3NjAzNTEyOGNjYjg0MzRkMTdjMjRmNjkyZTg2MzNkYmUzMDNmZjEzN2U3Nzg1NWYzZTk5YzY4MA
#security.jwt.expiration=86400000
#security.refresh.expiration=604800000
#security.jwt.user.generator=warfarm_BACKEND_ISSUER_DEV

#TODO configurar compresion en netty
server.compression.enabled=true
server.port=8080