spring.application.name=ARCANE-OUTERFIELDS
app.env=DEV

#R2DBC
spring.r2dbc.url=${R2DBC_URL:r2dbc:postgresql://db:5432/arcane?currentSchema=warfarm}
spring.r2dbc.username=${DATA_SOURCE_USERNAME}
spring.r2dbc.password=${DATA_SOURCE_PASSWORD}

#Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.url=${DATA_SOURCE_URL}
spring.flyway.user=${DATA_SOURCE_ADMIN_USERNAME}
spring.flyway.password=${DATA_SOURCE_PASSWORD}

#LOGINLEVEL
logging.level.org.springframework.security=DEBUG
logging.level.root=debug
logging.pattern.console=%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} level=%-5level app=${spring.application.name} env=${APP_ENV} pid=%property{PID} thread=%thread msg=%replace(%msg){'\\n','\\\\n'}%n

#TODO configurar compresion en netty
server.compression.enabled=true
server.port=8080